Added correct addOffer using Redux
EnjoyTheNoise/Joblify.Spa pull request #14
Opened 2019-05-12 19:00 UTC by Bartosz97

2019-05-12 21:21 UTC, EnjoyTheNoise commented
First of all: you didn't merge current dev into your branch
Second: did you test it?
Another thing is, you're redirecting by pushing using withRouter and history prop, while in dev we already have method of redirecting using connected-react-router. Can you explain why?

2019-05-13 19:26 UTC, Bartosz97 commented
1. Now, I pull the newest change from dev.
2. Yes, add offer work correctly

2019-05-25 09:30 UTC, EnjoyTheNoise requested changes
Again problems with package-lock, resolve it or don't create PR

2019-05-25 09:56 UTC, EnjoyTheNoise commented on src/actions/addOfferAction.js
> +export const getAllCategories = props => dispatch => {
what is the point of passing props in every single action?

2019-05-25 10:00 UTC, EnjoyTheNoise commented on src/actions/httpErrorAction.js
> +export const HTTP_401_ERROR = "HTTP_401_ERROR";
I know exactly from where did you get this code, but friendly reminder: we're using connected-react-router [https://github.com/supasate/connected-react-router/blob/master/FAQ.md#how-to-navigate-with-redux-action](url)

2019-05-29 18:26 UTC, merged