Added LoginForm and basic Navbar with HomePage.
EnjoyTheNoise/Joblify.Spa pull request #3
Opened 2019-04-03 11:28 UTC by Bartosz97

Added basic class structure for Navbar, HomePage and Login. Added Bootstrap v4 and React-Router-Dom.

2019-04-03 18:39 UTC, EnjoyTheNoise reviewed
Remarks:
- please add .vs folder to .gitignore
- what did you do in order to create 3,5k additions and deletions in package-lock?

2019-04-03 18:41 UTC, EnjoyTheNoise commented on src/App.js
>        <div className="App">
formatting here

2019-04-03 18:41 UTC, EnjoyTheNoise commented on src/App.js
> +        <Switch>
formatting here

2019-04-03 18:43 UTC, EnjoyTheNoise commented on src/containers/LoginFormContainer.js
> +    }
formatting (no new line)

2019-04-03 18:43 UTC, EnjoyTheNoise commented on src/containers/LoginFormContainer.js
> +      let fbCotent;
typo I believe?

2019-04-03 18:43 UTC, EnjoyTheNoise commented on src/containers/LoginFormContainer.js
> +      let fbCotent;
also gj for using let c:

2019-04-03 18:44 UTC, EnjoyTheNoise commented on src/containers/LoginFormContainer.js
> +            <div style={{
are we using inline styles or external css files?

2019-04-07 14:50 UTC, jskurzynska requested changes
You have to create this PR again, vs files are forbidden here. 
The easiest solution for you - remove this PR, jump to the version of branch without your changes, then create commit with gitignore (.vs should be added there) and only next commit should contain your changes (so probably you have to copy it - it will be the easiest solution)
Then I will check your PR again

2019-04-07 19:09 UTC, closed without merging

2019-04-07 19:09 UTC, Bartosz97 commented
I need create PR again